language: csharp
mono: none
dotnet: 1.0.0
sudo: required
dist: trusty
os:
  - linux
addons:
  apt:
    packages:
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8
      - zlib1g
env:
  matrix:
    - CLI_VERSION=Latest
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 0
branches:
  only:
    - master
    - dev
    - bld
script:
  - dotnet restore
  - dotnet test ./test/Certes.Tests/Certes.Tests.csproj