version: 1.0.1.{build}
build:
  verbosity: minimal

skip_tags: true

branches:
  # whitelist
  only:
    - master
    - dev
    - dev-azure

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0"

init:
  - git config --global core.autocrlf input

install:

build_script:
  - ps: $packageVersion = if ($env:APPVEYOR_REPO_BRANCH -eq "master") { "$($env:appveyor_build_version)" } else { "$($env:appveyor_build_version)-$($env:APPVEYOR_REPO_BRANCH)" }
  - ps: $env:CERTES_PACKAGE_VERSION = $packageVersion
  - ps: echo "Update Certes package version to $($packageVersion)"
  - ps: $packageJson = Get-Content -Raw .\src\Certes\project.json | ConvertFrom-Json
  - ps: $packageJson.version = $packageVersion
  - ps: $packageJson | ConvertTo-Json | Set-Content .\src\Certes\project.json
  - ps: echo "Update Certes.Cli package version to $($packageVersion)"
  - ps: $packageJson = Get-Content -Raw .\src\Certes.Cli\project.json | ConvertFrom-Json
  - ps: $packageJson.version = $packageVersion
  - ps: $packageJson.dependencies.Certes = $packageVersion
  - ps: $packageJson | ConvertTo-Json | Set-Content .\src\Certes.Cli\project.json
  - ps: echo "Update Certes.Azure package version to $($packageVersion)"
  - ps: $packageJson = Get-Content -Raw .\src\Certes.Azure\project.json | ConvertFrom-Json
  - ps: $packageJson.version = $packageVersion
  - ps: $packageJson.dependencies.Certes = $packageVersion
  - ps: $packageJson | ConvertTo-Json | Set-Content .\src\Certes.Cli\project.json
  - ps: echo "Update dependency versions for Certes.Tests"
  - ps: $packageJson = Get-Content -Raw .\test\Certes.Tests\project.json | ConvertFrom-Json
  - ps: $packageJson.dependencies.Certes = $packageVersion
  - ps: $packageJson.dependencies.'Certes.Cli' = $packageVersion
  - ps: $packageJson | ConvertTo-Json | Set-Content .\test\Certes.Tests\project.json
  - dotnet --info
  - dotnet restore
  - dotnet test ./test/Certes.Tests/project.json
  - dotnet pack -c release -o ./build/nuget ./src/Certes/project.json
  - dotnet pack -c release -o ./build/nuget ./src/Certes.Azure/project.json
  - dotnet publish -f netcoreapp1.0 -c release -o ./build/cli/bin ./src/Certes.Cli/project.json
  - ps: '"dotnet %~dp0bin/Certes.Cli.dll %* " | Set-Content .\build\cli\certes.bat'
  - 7z a build\certes-cli.zip .\build\cli\*.* -r

test: off

configuration: Release

artifacts:
    - path: build\nuget\Certes.$(CERTES_PACKAGE_VERSION).nupkg
      name: nupkg

    - path: build\nuget\Certes.Azure.$(CERTES_PACKAGE_VERSION).nupkg
      name: nupkg-azure
      
    - path: build\certes-cli.zip
      name: cli

deploy:
  - provider: GitHub
    release: v$(CERTES_PACKAGE_VERSION)
    description: 'Certes v$(CERTES_PACKAGE_VERSION)'
    auth_token:
      secure: B+lTI7i/tnZeg1ZSmho3HvOWjs0C4hptNy5cvWgF0Nn7b6v8nwT/mxEWVCfIJ7Fy
    artifact: nupkg,cli
    draft: false
    prerelease: false
    on:
      branch: master

  - provider: GitHub
    release: v$(CERTES_PACKAGE_VERSION)
    description: 'Certes v$(CERTES_PACKAGE_VERSION)'
    auth_token:
      secure: B+lTI7i/tnZeg1ZSmho3HvOWjs0C4hptNy5cvWgF0Nn7b6v8nwT/mxEWVCfIJ7Fy
    artifact: nupkg,cli
    draft: false
    prerelease: true
    on:
      branch: dev

  - provider: NuGet
    #server: http://www.nuget.org/api/v2/package                  # remove to push to NuGet.org
    api_key:
      secure: enjdo7AiXKaGhj8NC2k3wjQ9mGlU1jxABzG6tuphpM7dNaazlrSlvwR2H1kC4kr+
    skip_symbols: true
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: nupkg
    on:
      branch: master

  - provider: NuGet
    server: https://www.myget.org/F/dymetis/api/v2/package
    api_key:
      secure: RSdqUIwRSn8DI5xaa4iWBzOtYU6y3K9JRh07myQpAIRf5IhlwsZpFsnQOpCg1g7J
    skip_symbols: true
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: nupkg,nupkg-azure
    on:
      branch: dev,dev-azure
