version: 1.0.2.{build}
build:
  verbosity: minimal

skip_tags: true

skip_commits:
  files:
  - '*.md'

branches:
  # whitelist
  only:
    - master
    - dev
    - dev-azure

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0"

environment:
  certes__azure__servicePrincipal__tenantId:
    secure: 4FrR9+ARA8H+bLFFQDT4C1TAZv/LTO69vFpfjpqR5BVTedqgsZcey6xuS2TDA46l
  certes__azure__servicePrincipal__clientId:
    secure: s0tJTf4OqtsG0ze5ZL0g4kWcVw3oMnNiaepf0cwkh1U1s214jf1AdwGuFss2y7q7
  certes__azure__servicePrincipal__clientSecret:
    secure: IObP5jhbKBiEWg08kGjDNYhUBkOJw++2W3KqjsJT4t+16l5+dPxcTN4Pj4WSXJNC
  certes__azure__webApp__subscriptionId:
    secure: FSK01SfyZI0x6AX2XVDxcE6kUAmg4fYja2hsNcQNBxa1PBddSZtZ8rthvO5c8o/R
  certes__azure__webApp__resourceGroup: certes
  certes__azure__webApp__name: certes

init:
  - git config --global core.autocrlf input

install:

build_script:
  - dotnet --info
  - ps: $packageVersion = if ($env:APPVEYOR_REPO_BRANCH -eq "master") { "$($env:appveyor_build_version)" } else { "$($env:appveyor_build_version)-$($env:APPVEYOR_REPO_BRANCH)" }
  - ps: $env:CERTES_PACKAGE_VERSION = $packageVersion
  - ps: >-
      Get-ChildItem -Path ./ -Filter project.json -Recurse | foreach {
        $projectJson = Get-Content -Raw $_.FullName | ConvertFrom-Json
        if ($projectJson.version) { $projectJson.version = $packageVersion }
        if ($projectJson.dependencies -and $projectJson.dependencies.'Certes') { $projectJson.dependencies.'Certes' = $packageVersion }
        if ($projectJson.dependencies -and $projectJson.dependencies.'Certes.Cli') { $projectJson.dependencies.'Certes.Cli' = $packageVersion }
        if ($projectJson.dependencies -and $projectJson.dependencies.'Certes.Integration') { $projectJson.dependencies.'Certes.Integration' = $packageVersion }
        if ($projectJson.dependencies -and $projectJson.dependencies.'Certes.Integration.Azure') { $projectJson.dependencies.'Certes.Integration.Azure' = $packageVersion }
        $projectJson | ConvertTo-Json -Depth 100 -Compress | Set-Content $_.FullName
      }
  - dotnet restore
  - dotnet pack -c release -o ./build/nuget ./src/Certes/project.json
  - dotnet pack -c release -o ./build/nuget ./src/Certes.Integration/project.json
  - dotnet pack -c release -o ./build/nuget ./src/Certes.Integration.Azure/project.json
  - dotnet publish -f netcoreapp1.0 -c release -o ./build/cli/bin ./src/Certes.Cli/project.json
  - ps: '"dotnet %~dp0bin/Certes.Cli.dll %* " | Set-Content .\build\cli\certes.bat'
  - 7z a build\certes-cli.zip .\build\cli\*.* -r

test: off
test_script:
  - ps: pushd .\test\Certes.Tests
  - dotnet test
  - ps: popd

configuration: Release

artifacts:
    - path: build\nuget\Certes.$(CERTES_PACKAGE_VERSION).nupkg
      name: nupkg

    - path: build\nuget\Certes.Integration.$(CERTES_PACKAGE_VERSION).nupkg
      name: nupkg-int

    - path: build\nuget\Certes.Integration.Azure.$(CERTES_PACKAGE_VERSION).nupkg
      name: nupkg-int-azure
      
    - path: build\certes-cli.zip
      name: cli

deploy:
  - provider: GitHub
    release: v$(CERTES_PACKAGE_VERSION)
    description: 'Certes v$(CERTES_PACKAGE_VERSION)'
    auth_token:
      secure: B+lTI7i/tnZeg1ZSmho3HvOWjs0C4hptNy5cvWgF0Nn7b6v8nwT/mxEWVCfIJ7Fy
    artifact: nupkg,cli
    draft: false
    prerelease: false
    on:
      branch: master

  - provider: GitHub
    release: v$(CERTES_PACKAGE_VERSION)
    description: 'Certes v$(CERTES_PACKAGE_VERSION)'
    auth_token:
      secure: B+lTI7i/tnZeg1ZSmho3HvOWjs0C4hptNy5cvWgF0Nn7b6v8nwT/mxEWVCfIJ7Fy
    artifact: nupkg,cli
    draft: true
    prerelease: true
    on:
      branch: dev

  - provider: NuGet
    #server: http://www.nuget.org/api/v2/package                  # remove to push to NuGet.org
    api_key:
      secure: enjdo7AiXKaGhj8NC2k3wjQ9mGlU1jxABzG6tuphpM7dNaazlrSlvwR2H1kC4kr+
    skip_symbols: true
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: nupkg
    on:
      branch: master

  - provider: NuGet
    server: https://www.myget.org/F/dymetis/api/v2/package
    api_key:
      secure: RSdqUIwRSn8DI5xaa4iWBzOtYU6y3K9JRh07myQpAIRf5IhlwsZpFsnQOpCg1g7J
    skip_symbols: true
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: nupkg,nupkg-int,,nupkg-int-azure
    on:
      branch:
        - dev
        - dev-azure
